### PR TITLE
Update BlackBox runtime to 46

### PR DESCRIPTION
**Pull request by yakushabb**
- Update BlackBox runtime to 46
- Fix appdata papercuts
- Use better cleanup

### CODE REVIEW

**Comment by yakushabb** [comment]
@raggesilver I've updated BlackBox runtime to version 46 since runtime version 44 has reached end-of-life. Could you review changes?

**Comment by raggesilver** [comment]
Looks good, thanks for working on this!

**Comment by DaPigGuy** [comment]
The actual change to the runtime version seems to not have been pushed here :sweat_smile:

**Comment by raggesilver** [comment]
> The actual change to the runtime version seems to not have been pushed here 😅

Oh, what the hell? I'll fix this later today.

**Comment by yakushabb** [comment]
Sorry, my mistake :)

**Pull request merged**
